FROM maven:3.8.4-openjdk-17-slim as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY pom.xml /usr/src/app
COPY src/ /usr/src/app/src
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
RUN mvn package -Dmaven.test.skip=true
FROM openjdk:17-alpine
ENV JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -Dfile.encoding=UTF-8"
RUN addgroup --system spring && adduser --system spring && adduser spring spring
USER spring:spring
COPY --from=builder /usr/src/app/target/*.jar app.jar
EXPOSE 8080
ENV HOST=0.0.0.0
ENV PORT=8080
ENTRYPOINT ["java","-jar","app.jar"]